### PR TITLE
feat: support org peribolos

### PR DESCRIPTION
**Pull request by hi-rustin**
- 1. Support Multiple orgs
- 2. Support Multiple Teams
- 3. When pr merges, automatically sync

### CODE REVIEW

**Comment by hi-rustin** [comment]
/hold

Waiting self check.

**Comment by hi-rustin** [comment]
/hold cancel

Ready for review.

**Comment by hi-rustin** [comment]
/assign @Mini256 

PTAL~ thanks!

**Comment by hi-rustin** [comment]
@Mini256 Could you please take a look?

**Comment by Mini256** [comment]
> @Mini256 Could you please take a look?

OK，I am reviewing.

**Pull request merged**
